import React from "react";

const TermsModal = ({ isOpen, setIsOpen }) => {

    return (
        <>
          <div className={`justify-center items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none ${isOpen ? '' : 'hidden'}`}>
            <div className="relative w-11/12 my-6 mx-auto h-80vh">
              {/*content*/}
              <div className="border-0 rounded-lg shadow-lg relative flex flex-col w-full bg-white outline-none focus:outline-none p-5 md:p-12">
                {/*header*/}
                <div className="flex items-start justify-between border-solid border-blueGray-200 rounded-t">
                  <button
                    className="ml-auto bg-transparent border-0 text-black float-right text-5xl leading-none outline-none focus:outline-none"
                    onClick={() => setIsOpen(false)}
                  >
                    <span className="p-0">
                      ×
                    </span>
                  </button>
                </div>
                {/*body*/}
                <div className="relative flex-auto">
                    <p className="text-right font-bold underline">Last Modified: 14 December 2021</p>
                    <p className="text-center font-bold underline mt-5 text-2xl">Terms of Service</p>
                    <p className="text-left mt-5">Welcome to Republic Realm! Republic Realm is a platform that allows you to buy, sell, and display nonfungible tokens (“NFTs”). These Terms of Service (“Terms”) govern your use of services (collectively, the “Services”) provided by Republic Realm Inc. d/b/a Republic Realm (“we”, “us”, “Republic Realm”) through our website (www.republicrealm.com) (the “Website”). These Terms are a binding legal agreement between you or the entity you represent (“you”) and Republic Realm. A “user” is you or anyone who accesses, browses, or in any way uses the Services. These Terms refer to our privacy policy, incorporated into these Terms by reference, which also applies to your use of the Services and which sets out the terms on which we process any personal data or information we collect from you or that you provide to us (the “Privacy Policy”).</p>
                    <p className="text-left font-bold mt-5">Please read the Terms carefully before you start to use the Services offered on the Website. By using the Services, you accept and agree to be bound and abide by these Terms and our Privacy Policy. If you do not want to agree to these Terms or the Privacy Policy, you must not access or use the Services.</p>
                    <p className="text-left mt-5">The Services are offered and available to users who are 18 years of age or older. By using these Services, you represent and warrant that you are of legal age to form a binding contract with Republic Realm and meet the foregoing eligibility requirements. If you do not meet all of these requirements, you must cease access and use of the Services.</p>
                    <p className="text-left mt-5 font-bold text-xl">1. Changes to the Terms</p>
                    <p className="text-left mt-5">We reserve the right, in our sole discretion, to change, modify, add, or remove portions of these Terms at any time, without notice. Any changes or updates will be effective immediately upon posting to this page. You are expected to review these Terms regularly for changes, as they are binding on you. You can determine if changes have been made by checking the effective date at the top of these Terms. Your continued use of our Services following the posting of any changes to these Terms means you consent to such changes.</p>
                    <p className="text-left mt-5 font-bold text-xl">2. Accessing the Services</p>
                    <p className="text-left mt-5">By accessing or using the Services:</p>
                    <p className="text-left mt-5">(a) You acknowledge that you have read, understood, and accept these Terms and any additional documents or policies referred to in or incorporated into these Terms;</p>
                    <p className="text-left mt-5">(b) If these Terms have materially changed since you last accessed or used the Services, you acknowledge and agree that your continued access or use of the Services constitutes your acceptance of the revised Terms;</p>
                    <p className="text-left mt-5">(c) You represent and warrant that you are at least 18 years of age and have the right, authority, and capacity to enter into these Terms, either on behalf of yourself or the entity that you represent; and</p>
                    <p className="text-left mt-5">(d) You consent to receive communications from us electronically, and you agree that such electronic communications, notices, and postings satisfy any legal requirements that such communications be in writing.</p>
                    <p className="text-left mt-5 font-bold text-xl">3. Conditions of Service</p>
                    <p className="text-left mt-5">It is a condition of your use of the Services that the information you provide is correct, current, and complete. You are responsible for making all arrangements necessary for you to have access to the Services. You agree that we will not be liable to you for any unavailability, modification, suspension or discontinuance of the Services. The Services are provided exclusively for personal and noncommercial use.</p>
                    <p className="text-left mt-5 font-bold text-xl">4. Your Republic Realm Account</p>
                    <p className="text-left mt-5">You need to create an account with Republic Realm to use the Services. When you create an account, we will ask your for some information about yourself. We may require you, in our sole discretion, to provide additional information and/or documents. If you do not provide complete and accurate information and/or documents in response to such a request or requests, we may refuse to provide you with the Services.</p>
                    <p className="text-left mt-5">Your Republic Realm account is subject to the following conditions:</p>
                    <p className="text-left mt-5">* You may only open one account on Republic Realm. If we have a reasonable suspicion that you have opened multiple accounts on Republic Realm, we reserve the right to take whatever action we deem appropriate, including but not limited to closing and/or freezing your accounts.</p>
                    <p className="text-left">* Access: you understand and agree that access to your Republic Realm account is limited solely to you. You agree that you will not sell, rent, lease, or grant access to your Republic Realm account to any other person without our prior written permission.</p>
                    <p className="text-left">* Security: you understand and agree that you are solely responsible for maintaining the security of your account and control over any user names, passwords, or any other codes that you use to access the Services. Any unauthorized access to your account by third parties could result in the loss or theft of NFTs and/or funds held in your account and any associated accounts, including your linked bank account(s) and credit card(s). You understand and agree that you will not hold us responsible for managing and maintaining the security of your account. You further understand and agree that we are not responsible (and you will not hold us responsible) for any unauthorized access to or use of your account. You are responsible for monitoring your account. If you notice any unauthorized or suspicious activity in your account, please notify us immediately.</p>
                    <p className="text-left">* Trading Fees: by buying or selling a NFT on Republic Realm, you agree to pay all applicable fees and you authorize Republic Realm to automatically deduct fees directly from your payment. You will be provided with a breakdown of fees prior to your purchase or sale of a NFT.</p>
                    <p className="text-left">* Communication: you agree and understand that we will communicate with you via electronic means. To ensure that you receive all of our communications, you agree to keep your email address and telephone number current and notify us if there are any changes. You agree that any notices, agreements, disclosures, or other communications delivered to your email address on record are considered valid.</p>
                    <p className="text-left">* USD Balance: certain approved users may carry a balance in U.S. Dollars to facilitate transactions on the Republic Realm platform. You are the owner of your balance.</p>
                    <p className="text-left">* Unclaimed Property: if Republic Realm is holding funds in your account and has no record of your use of the Service for several years, we may be required, upon passage of applicable time periods, to report these funds as unclaimed property in accordance with the abandoned property and escheat laws. If this occurs, we will use reasonable efforts to give you written notice. If you fail to respond within seven business days or as required by law, we may be required to deliver any such funds to the applicable state or jurisdiction as unclaimed property. We reserve the right to deduct a dormancy fee or administrative fee from such unclaimed funds, as permitted by applicable law.</p>
                    <p className="text-left mt-5 font-bold text-xl">5. User Content</p>
                    <p className="text-left mt-5">The Site allows (1) users to create a profile where they can post certain information about themselves, link to other websites, and display NFTs that they own (collectively, “Profile Information”); and (2) artists or creators of NFTs (“NFT Creators”) to post their NFTs (“NFT Creations”), and bios (collectively, with Profile Information, “User Content”). All User Content must comply with these Terms of Use.</p>
                    <p className="text-left mt-5">Any Profile Information you post to the Site will be considered non-confidential and non-proprietary. By providing any User Content on the Website, you grant us and our affiliates and our respective licensees, successors, and assigns the right to use, reproduce, modify, perform, display, distribute, retransmit, publish, broadcast, and otherwise disclose to third parties any such material for any purpose. You represent and warrant that (1) you own and control all rights in and to your User Content and have the right to grant such licenses to us and our affiliates and our respective licensees, successors, and assigns; and (2) all of your User Content does and will comply with these Terms of Use.</p>
                    <p className="text-left mt-5">You understand and agree that you are responsible for any User Content you submit or contribute, and you, and not Republic Realm, have full responsibility for such content, including its legality, reliability, accuracy, and appropriateness. We are not responsible or liable to any third party for the content, accuracy, or appropriateness of any User Content posted by you or any other user on the Site.</p>
                    <p className="text-left mt-5">If you are a NFT Creator, you hereby grant Republic Realm non-exclusive, worldwide, royalty-free licenses to:</p>
                    <p className="text-left mt-5">* use the artwork contained in your NFT Creation for purposes of minting, displaying and selling your NFT Creations;</p>
                    <p className="text-left">* use your name and image for marketing or promotional purposes;</p>
                    <p className="text-left">* use, copy, modify, distribute, publish, and otherwise transmit images from your NFT Creations for marketing or promotional purposes; and</p>
                    <p className="text-left">* use your biography and other public information about you to promote your NFT Creations.</p>
                    <p className="text-left mt-5">As a NFT Creator, you understand and agree that:</p>
                    <p className="text-left mt-5">* You are responsible for the accuracy and content of your NFT Creations;</p>
                    <p className="text-left">* Any NFT Creation that violates any of Republic Realm’s policies may be obfuscated or deleted by Republic Realm, in our sole discretion;</p>
                    <p className="text-left">* You will not use the artwork incorporated into your NFT Creations for the creation of additional non-fungible tokens;</p>
                    <p className="text-left">* You will respect the intellectual property of others; and</p>
                    <p className="text-left">* You will not coordinate pricing with other NFT Creators.</p>
                    <p className="text-left mt-5">We reserve the right, in our sole discretion, to prohibit you from uploading your NFT Creations. Although we are not required to monitor any User Content, we may, in our sole discretion, remove User Content at any time and for any reason without notice. Republic Realm may monitor User Content to detect and prevent fraudulent activity or violation of these Terms of Use.</p>
                    <p className="text-left mt-5 font-bold text-xl">6. Prohibited Uses</p>
                    <p className="text-left mt-5">You may use the Services only for lawful purposes and in accordance with these Terms. We are under no obligation to enforce the Terms on your behalf against another user. We encourage you to let us know if you believe another user has violated the Terms or otherwise engaged in prohibited or illegal conduct. You agree not to, and will not assist, encourage, or enable others to use the Services:</p>
                    <p className="text-left mt-5">* For any commercial purpose, except as expressly permitted under these Terms.</p>
                    <p className="text-left mt-5">* In a manner that is defamatory, abusive, threatening, offensive, an invasion of a right of privacy of another person or could otherwise be reasonably expected to harm any person or entity.</p>
                    <p className="text-left mt-5">* To violate any applicable national, regional, federal, state, local, or international law or regulation, or to encourage any such violation or any illegal activity.</p>
                    <p className="text-left mt-5">* To create, send, knowingly receive, display, transmit, use, or reuse any material which may:</p>
                    <p className="text-left mt-5">&nbsp;&nbsp;&nbsp;- Infringe any patent, trademark, trade secret, copyright, or other intellectual property rights of any other person;</p>
                    <p className="text-left mt-5">&nbsp;&nbsp;&nbsp;- Violate or assists in the violation of legal rights (including the rights of publicity and privacy) of others or contain any material that could give rise to any civil or criminal liability under applicable laws or regulations, or that otherwise may be in conflict with these Terms or our Privacy Policy; or</p>
                    <p className="text-left mt-5">&nbsp;&nbsp;&nbsp;- Be likely to deceive or confuse any person.</p>
                    <p className="text-left mt-5">&nbsp;&nbsp;&nbsp;- Violate these Terms or any other rules or policies posted by us on our website or otherwise provided to you.</p>
                    <p className="text-left mt-5">&nbsp;&nbsp;&nbsp;- Reverse engineer, reverse compile, reverse assemble or perform any other operation with the Services that would reveal any source code, trade secrets, know-how or other proprietary information.</p>
                    <p className="text-left mt-5">&nbsp;&nbsp;&nbsp;- Modify, adapt, appropriate, reproduce, distribute, translate, create derivative works or adaptations of, publicly display, sell, trade, or in any way exploit the Services, except as expressly authorized by Republic Realm.</p>
                    <p className="text-left mt-5">&nbsp;&nbsp;&nbsp;- Remove or modify any copyright, trademark, or other proprietary rights notice that appears on any portion of the Services or on any materials printed or copied from the Services.</p>
                    <p className="text-left mt-5">&nbsp;&nbsp;&nbsp;- Record, process, harvest, collect, or mine information about other users.</p>
                    <p className="text-left mt-5">&nbsp;&nbsp;&nbsp;- oAccess, retrieve, or index any portion of the Services for purposes of constructing or populating a searchable database.</p>
                    <p className="text-left mt-5">&nbsp;&nbsp;&nbsp;- Use any robot, spider, or other automatic device, process, or means to access the Services for any purpose.</p>
                    <p className="text-left mt-5">&nbsp;&nbsp;&nbsp;- Use the Services to transmit any computer viruses, worms, defects, Trojan horses, or other items of a destructive nature (collectively, “Viruses”).</p>
                    <p className="text-left mt-5">&nbsp;&nbsp;&nbsp;- Use the Services to violate the security of any computer network, crack passwords or security encryption codes.</p>
                    <p className="text-left mt-5">&nbsp;&nbsp;&nbsp;- Remove, circumvent, disable, damage, or otherwise interfere with any security-related features or other restrictions of the Services.</p>
                    <p className="text-left mt-5">&nbsp;&nbsp;&nbsp;- Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Services, the server on which the Services is stored, or any server, computer, or database connected to the Services.</p>
                    <p className="text-left mt-5">&nbsp;&nbsp;&nbsp;- Attack the Services via a denial-of-service attack or a distributed denial-of-service attack.</p>
                    <p className="text-left mt-5">&nbsp;&nbsp;&nbsp;- Otherwise attempt to interfere with the proper working of the Services. The restrictions above only apply to the extent permissible under applicable law. Nevertheless, you agree not to act contrary to the restrictions (even if permissible under applicable law) without providing 30 days’ prior written notice to us at hello@republicrealm.com, together with any information that we may reasonably require in order to give us an opportunity to provide alternative remedies or otherwise accommodate you at our sole discretion.</p>
                    <p className="text-left mt-5 font-bold text-xl">7. IP Ownership</p>
                    <p className="text-left mt-5">We, or an entity affiliated with us, own the Services and all of our trademarks, logos, and branding in connection with the Services (“Republic Realm Content”), including current and future proprietary rights of every kind and nature however denominated throughout the world, registered or unregistered, associated with such Republic Realm Content and the Services (collectively, “Republic Realm IP”). Except as expressly and unambiguously provided herein, we do not grant you any express or implied rights, and all rights in and to the Republic Realm IP are retained by us.</p>
                    <p className="text-left mt-5">Outside the Republic Realm Content, all other trademarks, product names, and logos on the Site are the property of their respective owners and may not be copied, imitated, or used, in whole or in part, without the permission of the applicable trademark holder. Without limiting the foregoing, if you believe that third-party material hosted by Republic Realm infringes your copyright or trademark rights, please file a notice of infringement by contacting Republic Realm’s Copyright Agent at hello@republicrealm.com. </p>
                    <p className="text-left mt-5">In such event, please provide Republic Realm’s Copyright Agent with the following information: (1) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; (2) a description of the copyrighted work that you claim has been infringed; (3) a description of the location on Site of the material that you claim is infringing; (4) your address, telephone number and e-mail address; (5) a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent or the law; and (6) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf.</p>
                    <p className="text-left mt-5">Republic Realm’s policy is to suspend or terminate the account of repeat copyright infringers. Republic Realm’s response may depend on relevant aggravating or mitigating circumstances, but generally we will terminate an account if it is the subject of three valid infringement notices.</p>
                    <p className="text-left mt-5 font-bold text-xl">8. Limited License.</p>
                    <p className="text-left mt-5">We grant you a personal, limited, revocable, non-exclusive and non-transferable license to access and use the Services subject to the restrictions set out in these Terms (the “Limited License”). This Limited License is exclusive to you and you may not sublicense the usage of the Services.</p>
                    <p className="text-left mt-5 font-bold text-xl">9. Links to other Sites.</p>
                    <p className="text-left mt-5">If there are other websites and resources linked to the Services, these links are provided only for the convenience of our users. We have no control over the contents of those websites or resources, and therefore cannot accept responsibility for them or for any loss or damage that may arise from your use of them. If you decide to access any of the third-party websites linked to the Services, you do so entirely at your own risk and subject to the Terms and conditions of use for such websites.</p>
                    <p className="text-left mt-5">Republic Realm may rely on third-party platforms, including but not limited to MetaMask and/or Opensea to perform Republic Realm transactions. Our Site may contain links to third-party websites or applications (collectively, “Third Party Sites”). Republic Realm does not own or control Third Party Sites. You understand and agree that your use of any Third Party Site is subject to any terms of use and/or privacy policy provided by such Third Party Site. Republic Realm is not a party to any such agreement. You should review any terms of use and/or privacy policy provided by such Third Party Site and should make whatever investigation you feel necessary or appropriate before proceeding with any transaction with any third party.</p>
                    <p className="text-left mt-5">Republic Realm provides these Third Party Sites only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third Party Sites, or their products or services. You use all links in Third Party Sites at your own risk. When you leave our Site, our Agreement and policies no longer govern. We may, but are not obligated to, warn you that you are leaving our Site.</p>
                    <p className="text-left mt-5">Some transactions on our site may be facilitated and run by Metamask and/or Opensea. Any such transactions are governed by the Metamask or Opensea Terms of Service and/or Privacy Policy, as applicable.</p>
                    <p className="text-left mt-5 font-bold text-xl">10. No Guarantee of Service.</p>
                    <p className="text-left mt-5">Although we hope to make the Services available at all times in the future, there may be times when we need to disable the Services either temporarily or permanently. The Services may be modified, updated, interrupted, suspended, or discontinued at any time without notice or liability. Keep this in mind as Republic Realm will not be liable if all or any part of the Services are unavailable at any time, for any period of time. Also, from time to time, we may restrict access to some parts of the Services, or the entire Services, to users. We cannot and do not make any representations or warranties with respect to the devices you use to access or use the Services, including with respect to device compatibility.</p>
                    <p className="text-left mt-5 font-bold text-xl">11. Terms of Sale</p>
                    <p className="text-left mt-5">By placing a bid or an order on or through Republic Realm, you agree that you are submitting a binding offer to purchase such NFT or Service. Your order is accepted and confirmed once purchase is complete, and MetaMask displays the Confirmation Message ("Confirmation Message"). YOU HEREBY EXPRESSLY AGREE THAT THE SUPPLY OF A NFT COMMENCES WHEN THE CONFIRMATION MESSAGE IS DISPLAYED.</p>
                    <p className="text-left mt-5">No refunds or returns are permitted except with respect to any statutory warranties or guaranties that cannot be excluded or limited by law.</p>
                    <p className="text-left mt-5">NFT Creators may choose to provide certain rights to holders of their NFTs, which may include, but is not limited to, physical items, special access, or other exclusive content (collectively, “Additional Items”). Any Additional Items will be provided directly to you from the NFT Creator; Republic Realm has no involvement in such transactions and is not a party to such transactions. Notwithstanding the above, Republic Realm may publish a description of the Additional Items on its website on behalf of the NFT Creator. If you own a NFT that entitles you to Additional Items, you hereby consent to Republic Realm sharing your contact information with the NFT Creator to facilitate delivery of your Additional Items. Unless otherwise stated, transactions on the secondary market are only for NFTs and do not grant the purchaser the right to any Additional Items. </p>
                    <p className="text-left mt-5 font-bold text-xl">12. General Waiver; Assumption of Risk</p>
                    <p className="text-left mt-5">Republic Realm does not give investment advice, endorsement, analysis or recommendations with respect to any securities and is not a registered broker-dealer, funding portal or investment advisor. Any securities referenced here are being offered by, and all information included on this Website related to such securities is the responsibility of, the applicable issuer of such securities. The intermediary (if any) facilitating the offering will be identified in an issuer’s offering documentation. Any historical returns, expected returns, or probability projections may not reflect actual future performance. All securities involve risk and may result in partial or total loss. Republic Realm is not being compensated for hosting this Website. No offers are being made to any person in any jurisdiction where the provision or use thereof would be contrary to applicable laws, rules or regulations of any governmental authority or where Republic Realm is not authorized to provide such information or services. All users – persons or entities – accessing the Services do so on their own initiative and are responsible for compliance with applicable local laws and regulations. Nothing contained in the Services constitutes investment, financial, accounting, tax or legal advice; nor should be considered an offer, solicitation of an offer or advice to buy or sell securities.</p>
                    <p className="text-left mt-5">In purchasing a NFT from Republic Realm you acknowledge and agree that:</p>
                    <p className="text-left mt-5 font-bold">NEITHER REPUBLIC REALM NOR ANY OF ITS AFFILIATES AND THEIR OFFICERS, DIRECTORS, MANAGER(S), EMPLOYEES, AGENTS, SHAREHOLDERS/MEMBERS MAKE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE NFTs, INCLUDING ANY (A) WARRANTY OF MERCHANTABILITY; (B) WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE; (C) WARRANTY OF TITLE; OR (D) WARRANTY AGAINST INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS OF A THIRD PARTY; WHETHER EXPRESS OR IMPLIED BY LAW, COURSE OF DEALING, COURSE OF PERFORMANCE, USAGE OF TRADE OR OTHERWISE.</p>
                    <p className="text-left mt-5">You shall take all statements, recommendations, data, opinions, documents, and the like on an as-is basis and rely on your own counsel, third-party service providers and judgment in connection therewith.</p>
                    <p className="text-left mt-5 font-bold">IN NO EVENT SHALL REPUBLIC REALM OR ANY OF ITS AFFILIATES AND THEIR OFFICERS, DIRECTORS, MANAGER(S), EMPLOYEES, AGENTS, SHAREHOLDERS/MEMBERS BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, WHETHER UNDER ANY TORT, CONTRACT, NEGLIGENCE, STRICT LIABILITY, OR OTHER LEGAL OR EQUITABLE THEORY WHATSOEVER, INCLUDING WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, INTELLECTUAL PROPERTY INFRINGEMENT, PRICE DEPRECIATION, LEGAL OR REGULATORY ENFORCEMENT, BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, AND THE LIKE, ARISING OUT OF THIS AGREEMENT, EVEN IF REPUBLIC HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. </p>
                    <p className="text-left mt-5 font-bold">THE FOREGOING DOES NOT AFFECT ANY WARRANTIES THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</p>
                    <p className="text-left mt-5">This NFT sale is not intended to be an offering or sale of securities, swaps on either securities or commodities or a financial instrument of any kind as may be determined by any law, rule, or regulation. Purchases and sales of NFTs may not be subject to the protections of any laws governing those types of financial instruments. This document and all other content, including without limitation on https://www.republicrealm.com/, do not constitute a prospectus or offering document, and are not an offer to sell.</p>
                    <p className="text-left mt-5">In the event that you deposit digital assets or NFTs into an incorrect address, Republic Realm may not have the ability, and is under no obligation or duty, to return such digital assets or NFTs to you. This section applies regardless of whether Republic Realm controls the destination address.</p>
                    <p className="text-left mt-5">**Please note: exceptions to this section may be considered and made on a case-by-case basis and in Republic Realm’s sole discretion.**</p>
                    <p className="text-left mt-5">Republic Realm does not give any advice or recommendation regarding NFTs, including, but not limited to, the suitability and/or appropriateness of, and investment strategies for, the purchase of the NFTs for financial investment purposes. You are solely responsible for determining the nature, potential value, suitability, and appropriateness of your purchase of the NFTs for yourself for any purpose. The NFTs are not designed for investment purposes and Republic Realm does not give any advice or recommendation that the NFTs are to be considered a type of financial investment by any law, rule, or regulation. With respect to your purchase of the NFTs, you acknowledge and agree that you are not expecting to profit from the NFTs based on any efforts by Republic Realm or its affiliates. The purchase of a NFT is a non-reversible and non-refundable event. Republic Realm shall have no obligation or liability for the secure custody or use of the NFT and any losses arising from such custody or use or solely the purchasers. </p>
                    <p className="text-left mt-5">Please note the following risks in accessing or using Republic Realm: The price and liquidity of blockchain assets, including NFTs, are extremely volatile and may be subject to large fluctuations; fluctuations in the price of other digital assets could materially and adversely affect NFTs, which may also be subject to significant price volatility; legislative and regulatory changes or actions at the state, federal, or international level may adversely affect the use, transfer, exchange, and value of NFTs; NFTs are not legal tender and are not backed by the government; transactions in NFTs may be irreversible, and, accordingly, losses due to fraudulent or accidental transactions may not be recoverable; some transactions in NFTs shall be deemed to be made when recorded on a public ledger, which is not necessarily the date or time that you initiated the transaction; the value of NFTs may be derived from the continued willingness of market participants to exchange fiat currency or digital assets for NFTs, which may result in the potential for permanent and total loss of value of a particular NFT should the market for that NFT disappear; the nature of NFTs may lead to an increased risk of fraud or cyber-attack, and may mean that technological difficulties experienced by Republic Realm may prevent the access to or use of your digital assets and/ or personal information; and changes to any third party sites may create a risk that your access to and use of Republic Realm will suffer.</p>
                    <p className="text-left mt-5">You are solely responsible for determining the nature, potential value, suitability, and appropriateness of these risks for yourself. You access and use Republic Realm at your own risk; however, you also acknowledge that this brief statement does not disclose all of the risks associated with NFTs and other digital assets. You agree and understand that Republic Realm will not be responsible for any communication failures, disruptions, errors, distortions or delays it may experience when using, selling or promoting NFTs, however caused. </p>
                    <p className="text-left mt-5">You hereby expressly waive and release any and all claims, now known or hereafter known, against Republic Realm, its affiliates and their officers, directors, manager(s), employees, agents, shareholders/members (collectively, "Releasees"), related to the NFTs, whether arising out of the ordinary negligence of Republic Realm or any Releasees or otherwise. You covenant not to make or bring any such claim against Republic Realm or any other Releasee, and forever release and discharge Republic Realm and all other Releasees from liability under such claims. </p>
                    <p className="text-left mt-5 font-bold text-xl">13. Disclaimer of Warranties.</p>
                    <p className="text-left mt-5">REPUBLIC REALM HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR PURPOSE. THE SERVICES ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. REPUBLIC REALM DOES NOT GUARANTEE THE ACCURACY, TIMELINESS, COMPLETENESS OR USEFULNESS OF THE SERVICES OR ANY CONTENT. YOU AGREE TO USE THE SERVICES AT YOUR OWN RISK.</p>
                    <p className="text-left mt-5 font-bold text-xl">14. Limitation of Liability </p>
                    <p className="text-left mt-5">YOU ACKNOWLEDGE THAT YOUR ACCESS TO AND USE OF THE SERVICES AND ANY RELIANCE UPON EITHER IS AT YOUR SOLE RISK TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL REPUBLIC REALM BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH THE SERVICES, WHETHER OR NOT REPUBLIC REALM HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, ON ANY THEORY OF LIABILITY (INCLUDING CONTRACT, TORT INCLUDING NEGLIGENCE, OR HOWSOEVER OTHERWISE) ARISING OUT OF, IN CONNECTION WITH, OR RESULTING FROM THE SERVICES. YOU SPECIFICALLY ACKNOWLEDGE THAT DOWN-TIME AND COMPUTER VIRUSES ARE RISKS INHERENT IN THE USE OF THE INTERNET AND SOFTWARE PRODUCTS, AND YOU AGREE TO ASSUME RESPONSIBILITY FOR ANY HARM OR DAMAGES OF ANY KIND OR CHARACTER WHATSOEVER RESULTING FROM THESE POSSIBLE HARMS. YOU ALSO SPECIFICALLY ACKNOWLEDGE THAT YOU MAY BE DISCLOSING SENSITIVE, PRIVATE AND CONFIDENTIAL INFORMATION ABOUT YOURSELF IN YOUR USE OF THE SERVICES AND YOU AGREE TO ASSUME RESPONSIBILITY FOR ANY HARM OR DAMAGES OF ANY KIND OR CHARACTER WHATSOEVER RESULTING FROM YOUR RELEASE OF SUCH CONTENT. IF YOU ARE DISSATISFIED WITH THE SERVICES OR WITH ANY OF THESE TERMS, OR FEEL WE HAVE BREACHED THESE TERMS, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SERVICES. OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING FROM OR RELATING TO THESE TERMS OR USE OF THE SERVICES SHALL NOT EXCEED THE GREATER OF (i) THE AMOUNT PAID BY YOU FOR THE SERVICES IN THE SIX (6) MONTHS PRECEDING THE APPLICABLE CLAIM, IF ANY OR (ii) $100. IT IS THE INTENTION OF YOU AND US THAT THIS PROVISION BE CONSTRUED BY A COURT AS BEING THE BROADEST LIMITATION OF LIABILITY CONSISTENT WITH APPLICABLE LAW. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF INCIDENTAL, CONSEQUENTIAL OR OTHER TYPES OF DAMAGES, SO SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</p>
                    <p className="text-left mt-5 font-bold text-xl">15. Indemnification.</p>
                    <p className="text-left mt-5">You shall indemnify and hold harmless Republic Realm, its affiliates and licensors and their respective officers, directors, employees, contractors, agents, licensors and suppliers from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses or fees (including reasonable attorneys’ fees) resulting from (i) your violation of these Terms, (ii) your use or access of the Services, (iii) your violation of any third party right, including without limitation, any intellectual property right or right of publicity, (iv) any claim that your use of the Services caused damage to a third party or (v) from any decisions or investments that you make based on the Services or through any other investment vehicle referenced via the Services.</p>
                    <p className="text-left mt-5 font-bold text-xl">16. Governing Law.</p>
                    <p className="text-left mt-5">All matters relating to the Website, the Service and these Terms (including the Privacy Policy), and any dispute or claim arising therefrom or related thereto (in each case, including non-contractual disputes or claims) shall be governed by the laws of the State of New York, without respect to its conflict of laws principles. You agree to submit to the personal jurisdiction of the federal and state courts located in New York County, New York.</p>
                    <p className="text-left mt-5 font-bold text-xl">17. Arbitration and Class Action Waiver.</p>
                    <p className="text-left mt-5">A. Arbitration. READ THIS SECTION CAREFULLY BECAUSE IT REQUIRES THE PARTIES TO ARBITRATE THEIR DISPUTES AND LIMITS THE MANNER IN WHICH YOU CAN SEEK RELIEF FROM REPUBLIC REALM. For any dispute with Republic Realm, you agree to first contact us at hello@republicrealm.com and attempt to resolve the dispute with us informally. In the unlikely event that Republic Realm has not been able to resolve a dispute it has with you after 60 days, we each agree to resolve any claim, dispute, or controversy (excluding any claims for injunctive or other equitable relief as provided below) arising out of or in connection with or relating to this Agreement, or the breach or alleged breach thereof (collectively, “Claims”), by binding arbitration by JAMS, under the Optional Expedited Arbitration Procedures then in effect for JAMS, except as provided herein. JAMS may be contacted at www.jamsadr.com. The arbitration will be conducted in New York County, New York, unless you and Republic Realm agree otherwise. If you are using the Services for commercial purposes, each party will be responsible for paying any JAMS filing, administrative and arbitrator fees in accordance with JAMS rules, and the award rendered by the arbitrator shall include costs of arbitration, reasonable attorneys’ fees and reasonable costs for expert and other witnesses. If you are an individual using the Services for non-commercial purposes: (i) JAMS may require you to pay a fee for the initiation of your case, unless you apply for and successfully obtain a fee waiver from JAMS; (ii) the award rendered by the arbitrator may include your costs of arbitration, your reasonable attorneys’ fees, and your reasonable costs for expert and other witnesses; and (iii) you may sue in a small claims court of competent jurisdiction without first engaging in arbitration, but this does not absolve you of your commitment to engage in the informal dispute resolution process. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. Nothing in this Section shall be deemed as preventing Republic Realm from seeking injunctive or other equitable relief from the courts as necessary to prevent the actual or threatened infringement, misappropriation, or violation of our data security, intellectual property rights or other proprietary rights.</p>
                    <p className="text-left mt-5">B. Class Action/Jury Trial Waiver. WITH RESPECT TO ALL PERSONS AND ENTITIES, REGARDLESS OF WHETHER THEY HAVE OBTAINED OR USED THE SERVICES FOR PERSONAL, COMMERCIAL OR OTHER PURPOSES, ALL CLAIMS MUST BE BROUGHT IN THE PARTIES’ INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION, COLLECTIVE ACTION, PRIVATE ATTORNEY GENERAL ACTION OR OTHER REPRESENTATIVE PROCEEDING. THIS WAIVER APPLIES TO CLASS ARBITRATION, AND, UNLESS WE AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON’S CLAIMS. YOU AGREE THAT, BY ENTERING INTO THIS AGREEMENT, YOU AND REPUBLIC REALM ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION, COLLECTIVE ACTION, PRIVATE ATTORNEY GENERAL ACTION, OR OTHER REPRESENTATIVE PROCEEDING OF ANY KIND.</p>
                    <p className="text-left mt-5 font-bold text-xl">18. General Terms.</p>
                    <p className="text-left mt-5">These Terms constitute the sole and entire agreement between you and Republic Realm with respect to the Services and supersede all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral, with respect to the Services. No waiver of these Terms by Republic Realm shall be deemed a further or continuing waiver of such term or condition or any other term or condition, and any failure of Republic Realm to assert a right or provision under these Terms shall not constitute a waiver of such right or provision. If any provision of these Terms is held by a court of competent jurisdiction to be invalid, illegal, or unenforceable for any reason, such provision shall be modified to reflect the parties’ intention or eliminated to the minimum extent such that the remaining provisions of the Terms will continue in full force and effect. The Terms, and any rights or obligations hereunder, are not assignable, transferable, or sublicensable by you except with Republic Realm’s prior written consent, but may be assigned or transferred by us without restriction. Any attempted assignment by you shall violate these Terms and be void. The section titles in the Terms are for convenience only and have no legal or contractual effect.</p>
                    <p className="text-left mt-5 font-bold text-xl">19. Contact.</p>
                    <p className="text-left mt-5">All feedback, comments, requests for technical support, and other communications relating to the Services should be directed to: hello@republicrealm.com. By sending us any ideas, suggestions, documents or proposals (“Feedback”), you agree that (i) your Feedback does not contain the confidential or proprietary information of third-parties, (ii) we are under no obligation of confidentiality, express or implied, with respect to the Feedback, (iii) we may have something similar to the Feedback already under consideration or in development that is owned by us, and (iv) you grant us an irrevocable, non-exclusive, royalty-free, perpetual, worldwide license to use, modify, prepare derivative works, publish, distribute and sublicense the Feedback, and you irrevocably waive, and cause to be waived, against Republic Realm and its users any claims and assertions of any moral rights contained in such Feedback.</p>
                    </div>
                {/*footer*/}
              </div>
            </div>
          </div>
          <div className={`opacity-70 fixed inset-0 z-40 bg-black ${isOpen ? '' : 'hidden'}`} onClick={() => setIsOpen(false)}></div>
        </>
    )
}

export default TermsModal;